FROM ubuntu:18.04
LABEL maintainer="sailresearch"
LABEL repository="transformers-dapr"

RUN apt update && \
    apt install -y bash \
                   build-essential \
                   git \
                   curl \
                   ca-certificates \
                   python3.7 \
                   python3-pip && \
    rm -rf /var/lib/apt/lists
RUN python3.7 -m pip install --no-cache-dir --upgrade pip && \
    python3.7 -m pip install --no-cache-dir --upgrade pip && \
    python3.7 -m pip install --no-cache-dir \
    jupyter \
    tensorflow-cpu \
    torch

WORKDIR /workspace
COPY . transformers/
RUN cd transformers/ && \
    python3.7 -m pip install --no-cache-dir .

CMD ["/bin/bash"]